# Generated by Django 4.2 on 2023-05-22 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.city')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=6)),
                ('cure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.cure')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.pharmacy')),
            ],
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='cures',
            field=models.ManyToManyField(through='mainapp.Place', to='mainapp.cure'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='street',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.street'),
        ),
        migrations.AddField(
            model_name='cure',
            name='pharmacies',
            field=models.ManyToManyField(through='mainapp.Place', to='mainapp.pharmacy'),
        ),
    ]
